### ISSUE TITLE
[1.09.scm]

### ISSUE THREAD

**Issue by ghost** [jlollis/sicp-solutions#1]
https://github.com/jlollis/sicp-solutions/blob/master/Chapter%201%20Exercises/1.09.scm

Hey there! I'm a computer science student and recently I decided to study SICP. I was looking online for solutions to the various exercises in the book and I happened to stumble upon this repository. I kept referring to your solutions until I came to exercise 1.9. I wasn't too sure whether or not it was the correct solution. I tried it on my own and it didn't match, so I looked at other solutions on the internet:

https://codology.net/post/sicp-solution-exercise-1-9/ 
http://community.schemewiki.org/?sicp-ex-1.9

Let me know what you think :)
Also sorry in advance if I'm doing this wrong, I don't use GitHub very often :(

**Comment by jlollis** [comment]
Just seeing your comment. Thank you for pointing this out. It is fixed now. :)

**Comment by jlollis** [comment]
Just seeing your comment. Thank you for kindly pointing this out. It is fixed now. :)
